# This is not a complete Docker compose file.
# It contains parameters needed to set up a containerised MathJax application
# and connect it to a MediaWiki installation.

services:
  mediawiki:
    # ...
    depends_on:
      # Optional.
      mathjax:
        condition: service_started
    networks:
      mathjax:

  # If web frontend, e.g., nginx, is separate from MW installation. Otherwise, in mediawiki: service:
  frontend:
    # ...
    volumes:
      # Making MathJax available in the browser. Not necessary, if $wgmjUseCDN = true:
      # Frontend web root + $wgmjServiceExternalUrl:
      - mathjax:/var/www/js/mathjax:ro

  mathjax:
    build:
      context: ./services/cgi
      args:
        SRC_LANG: node
        # Add mathjax@4 and a font package if you want to serve mahjax to users' browsers to make math interactive:
        NODE: >
          mathjax@4
          @mathjax/mathjax-asana-font @mathjax/mathjax-bonum-font @mathjax/mathjax-dejavu-font @mathjax/mathjax-fira-font
          @mathjax/mathjax-modern-font @mathjax/mathjax-newcm-font @mathjax/mathjax-pagella-font @mathjax/mathjax-schola-font
          @mathjax/mathjax-stix2-font @mathjax/mathjax-termes-font @mathjax/mathjax-tex-font
        GIT: https://github.com/alex-mashin/MathJaxTeX2MathML.git
        COMMAND: /usr/bin/node /usr/local/bin/MathJaxTeX2MathML/tex2mml.cjs -l "$$lang"
        VERSION_COMMAND: /usr/bin/node /usr/local/bin/MathJaxTeX2MathML/tex2mml.cjs -v
        CONTENT_TYPE: text/html
    environment:
      ERRORS: FATAL
    restart: unless-stopped
    tmpfs:
      - /tmp
    volumes:
      # Mount and share this volume with web server frontend if you want to serve mahjax to users' browsers to make math interactive:
      - mathjax:/usr/local/bin/node_modules:ro
    networks:
      # This network ought to be shared with CMS:
      mathjax:
    deploy:
      resources:
        limits:
          memory: 256m

  # ...

volumes:
  # ...configs:
  mathjax:

networks:
  # ...configs:
  mathjax: